<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.testzombie.demo</groupId>
    <artifactId>testzombie-example-appium-ios</artifactId>
    <version>1.0.0</version>
    <name>TestZombie Appipum iOS Mutation Demo</name>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <appium.java.client.version>10.1.1</appium.java.client.version>
        <junit.version>6.1.2</junit.version>
        <slf4j.version>2.0.17</slf4j.version>
        <selenium.version>[4.46.0, 5.0.0)</selenium.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.testzombie</groupId>
            <artifactId>testzombie-lib-java</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>${appium.java.client.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.3</version>
                <configuration>
                    <useModulePath>false</useModulePath>
                    <systemPropertyVariables>
                        <testzombie.apikey>${testzombie.apikey}</testzombie.apikey>
                        <testzombie.email>${testzombie.email}</testzombie.email>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>defaults</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <testzombie.apikey></testzombie.apikey>
                <testzombie.email></testzombie.email>
            </properties>
        </profile>
    </profiles>
</project>
